name: Deploy and Test - Test Environment
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
concurrency:
  group: deployment
  cancel-in-progress: false
permissions:
  id-token: write
  contents: read
jobs:
  TestWorkflowBuild:
    uses: ./.github/workflows/build.yml
    with:
      deploy_env: TEST
      stack_prefix: ${{ vars.APP_STACK_PREFIX }}
    secrets:
      deploy_account: ${{ secrets.APP_DEPLOY_ACCOUNT_TEST }}
      dns_zone_domain: ${{ secrets.APP_DNS_ZONE_DOMAIN }}
      dns_zone_account: ${{ secrets.APP_DNS_ZONE_ACCOUNT }}
      dns_hosted_zone_id: ${{ secrets.APP_DNS_HOSTED_ZONE_ID }}
      test_dns_host: ${{ secrets.APP_TEST_DNS_HOST }}
      cognito_login_notification_email: ${{ secrets.APP_COGNITO_LOGIN_NOTIFICATION_EMAIL_TEST }}
      dev_blog_url: ${{ secrets.APP_DEV_BLOG_URL }}
      cognito_initial_username: ${{ secrets.APP_COGNITO_INITIAL_USERNAME }}
      cognito_initial_user_email: ${{ secrets.APP_COGNITO_INITIAL_USER_EMAIL }}
      cognito_initial_user_password: ${{ secrets.APP_COGNITO_INITIAL_USER_PASSWORD }}
      cognito_initial_user_given_name: ${{ secrets.APP_COGNITO_INITIAL_USER_GIVEN_NAME }}
      monitoring_email_list: ${{ secrets.APP_MONITORING_EMAIL_LIST_TEST }}
      homepage_title: ${{ secrets.APP_HOMEPAGE_TITLE }}
      aws_github_role: ${{ secrets.AWS_GITHUB_ROLE }}
      aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}

  TestWorkflowTest:
    needs: TestWorkflowBuild
    uses: ./.github/workflows/test.yml
    with:
      deploy_env: TEST
    secrets:
      dns_zone_domain: ${{ secrets.APP_DNS_ZONE_DOMAIN }}
      dev_blog_url: ${{ secrets.APP_DEV_BLOG_URL }}
      cognito_initial_user_email: ${{ secrets.APP_COGNITO_INITIAL_USER_EMAIL }}
      cognito_initial_user_password: ${{ secrets.APP_COGNITO_INITIAL_USER_PASSWORD }}
      cognito_initial_user_given_name: ${{ secrets.APP_COGNITO_INITIAL_USER_GIVEN_NAME }}
      initial_resume_docx_url: ${{ secrets.APP_INITIAL_RESUME_DOCX_URL }}
      initial_resume_source_code_url: ${{ secrets.APP_INITIAL_RESUME_SOURCE_CODE_URL }}
      test_resume_docx_url: ${{ secrets.APP_TEST_RESUME_DOCX_URL }}
      test_resume_source_code_url: ${{ secrets.APP_TEST_RESUME_SOURCE_CODE_URL }}
      test_modified_resume_docx_url: ${{ secrets.APP_TEST_MODIFIED_RESUME_DOCX_URL }}
      test_modified_resume_source_code_url: ${{ secrets.APP_TEST_MODIFIED_RESUME_SOURCE_CODE_URL }}
      homepage_source_code_url: ${{ secrets.APP_HOMEPAGE_SOURCE_CODE_URL }}
      test_dns_host: ${{ secrets.APP_TEST_DNS_HOST }}

  TestWorkflowDestroy:
    if: ${{ !cancelled() || vars.KEEP_TEST_ENV != true }}
    needs: TestWorkflowTest
    uses: ./.github/workflows/destroy.yml
    with:
      deploy_env: TEST
      stack_prefix: ${{ vars.APP_STACK_PREFIX }}
    secrets:
      deploy_account: ${{ secrets.APP_DEPLOY_ACCOUNT_TEST }}
      dns_zone_domain: ${{ secrets.APP_DNS_ZONE_DOMAIN }}
      dns_zone_account: ${{ secrets.APP_DNS_ZONE_ACCOUNT }}
      dns_hosted_zone_id: ${{ secrets.APP_DNS_HOSTED_ZONE_ID }}
      test_dns_host: ${{ secrets.APP_TEST_DNS_HOST }}
      cognito_login_notification_email: ${{ secrets.APP_COGNITO_LOGIN_NOTIFICATION_EMAIL_TEST }}
      dev_blog_url: ${{ secrets.APP_DEV_BLOG_URL }}
      cognito_initial_username: ${{ secrets.APP_COGNITO_INITIAL_USERNAME }}
      cognito_initial_user_email: ${{ secrets.APP_COGNITO_INITIAL_USER_EMAIL }}
      cognito_initial_user_password: ${{ secrets.APP_COGNITO_INITIAL_USER_PASSWORD }}
      cognito_initial_user_given_name: ${{ secrets.APP_COGNITO_INITIAL_USER_GIVEN_NAME }}
      monitoring_email_list: ${{ secrets.APP_MONITORING_EMAIL_LIST_TEST }}
      homepage_title: ${{ secrets.APP_HOMEPAGE_TITLE }}
      aws_github_role: ${{ secrets.AWS_GITHUB_ROLE }}
      aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}